# Note: URL must be filled in and it must be a direct download link. Look on https://youtube.com
# for tutorials on how to make a direct download link
packs:
  1:
    url:
  2:
    url:
  3:
    url:
  4:
    url:
  5:
    url:
  6:
    url:
  7:
    url:
  8:
    url:
  9:
    url: